name: Collect Source Code Archive

on:
  workflow_call:
    inputs:
      packages:
        description: 'Comma-separated list of packages to install and gather source code'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      packages:
        description: 'Comma-separated list of packages to install and gather source code'
        required: true
        default: ''

jobs:
  collect-source-code:
    runs-on: ubuntu-latest
    container:
      image: debian:12.8
    steps:
    - name: Add apt sources for deb-src
      shell: bash
      run: |
        sed -Ei "s/^Types: deb$/Types: deb deb-src/" /etc/apt/sources.list.d/debian.sources
        apt-get update

    - name: Find GPL/MPL licensed packages
      shell: bash
      env:
        PACKAGES: ${{ inputs.packages }}
      run: |
        OUTPUT_DIR="output"
        ARCHIVE_NAME="source_code.tar.gz"
        mkdir -p "$OUTPUT_DIR"
        cd "$OUTPUT_DIR"
        # Split comma-separated list into an array
        IFS=',' read -r -a PACKAGES_ARR <<< "$PACKAGES"
        # Collect missing packages
        # Download sources for GPL/MPL packages individually with error handling
        if [ ${#PACKAGES_ARR[@]} -gt 0 ]; then
          for PKG in "${PACKAGES_ARR[@]}"; do
            echo "Downloading source for $PKG"
            if ! apt-get source -q --download-only "$PKG"; then
              echo "Warning: Source not available for $PKG" >&2
            fi
          done
        fi
        cd ..
        tar -czf "$ARCHIVE_NAME" -C "$OUTPUT_DIR" .

    - name: Upload source code archive
      uses: actions/upload-artifact@v4  # v4
      with:
        name: source-code-archive
        path: source_code.tar.gz
